docs/css/theme-gloo.css
Fixes bad spacing on left side with mobile/pads
=> Fixes bad spacing on left side with mobile/pads

gloo/layouts/partials/custom-header.html, sqoop/layouts/partials/custom-header.html
This adds a new partial (custom-header) with the HubSpot tracking code.
=> Added hubspot javascript tracking code.

gloo/docs/user_guides/node_port.md
This is an update for https://github.com/solo-io/solo-docs/pull/35
=> updated nodeport docs

gloo/docs/installation/quick_start.md
1. Updated a **note** to be consistent.
2. Fixed a typo.
3. Minor re-order of a couple of sections to make the workflow clearer.
4. Minor rewording of a couple of sentences to make things a little clearer.
=> Minor edits for clarity and grammar

cloudbuild.yaml, supergloo/docs/installation/_index.md
Signed-off-by: scott weiss <sdw35@cornell.edu>
=> enable sg docs, update install doc

supergloo/docs/css/theme-gloo.css
=> set constraints on sidebar img

squash/docs/cli/_index.md, squash/docs/configuration/_index.md, squash/docs/debuggers/_index.md, squash/docs/overview/_index.md, squash/docs/secure_mode/_index.md, squash/docs/v1/_index.md
=> Squash ide notes

supergloo/docs/installation/_index.md, supergloo/docs/mesh/_index.md, supergloo/docs/mesh/install.md
depends on a new release of supergloo, which is blocked by a bugfix i'm working on.
do not merge yet, but feel free to review!
=> add docs for superglooo istio install

supergloo/docs/changelog/supergloo-changelog
Automatically generated docs for supergloo v0.3.2
=> Update docs for supergloo v0.3.2

gloo/docs/installation/_index.md
* Fix Broken link #156
* Fix Broken link #157
=> Fix Broken links

gloo/docs/enterprise/installation/install_glooctl.md, gloo/docs/enterprise/rate_limits_envoy/_index.md
- add a trial link for glooctl
- add a description for advanced rate limit
=> minor changes:

gloo/Makefile, gloo/docs/cli/glooctl_create_upstream.md, gloo/docs/installation/kubernetes/quick_start.md, gloo/docs/user_guides/_index.md, gloo/docs/user_guides/basic_routing.md, gloo/docs/user_guides/gloo_istio_mtls.md
So this is the first part of fixing the broken links. let's get this one in asap.
Will also work on the auto-generated docs that have broken links. That's WIP, but this PR good to go.
=> fixed links in non-generated docs

gloo/docs/user_guides/_index.md, gloo/docs/user_guides/basic_ingress.md, gloo/docs/user_guides/basic_routing.md, gloo/docs/user_guides/cloud_function/_index.md, gloo/docs/user_guides/external_api_routing.md, gloo/docs/user_guides/function_routing.md, gloo/docs/user_guides/gloo_istio_mtls.md, gloo/docs/user_guides/gloo_with_knative.md, gloo/docs/user_guides/node_port.md, gloo/docs/user_guides/tls_setup.md
We should really sort this out too:
https://github.com/solo-io/gloo/issues/577
As the guide here uses it
=> added user guide for setting up server TLS

gloo/docs/operator_guide/observability.md
Started cleanup so its more accurate. More to do; this is a start.
=> Updated Monitoring guide

gloo/Makefile, gloo/docs/dev/_index.md, gloo/docs/dev/example-proxy-controller.md, gloo/docs/introduction/architecture.md, gloo/docs/operator_guide/understanding_gloo_configuration.md
Last fix for https://github.com/solo-io/solo-docs/issues/170
=> Fix last broken links.

gloo/docs/changelog/gloo-changelog, gloo/docs/v1/github.com/solo-io/gloo/projects/gloo/api/v1/circuit_breaker.proto.sk.md, gloo/docs/v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins.proto.sk.md, gloo/docs/v1/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
Automatically generated docs for gloo v0.13.4
=> Update docs for gloo v0.13.4

gloo/docs.toml, gloo/docs/enterprise/basic_routing_console/_index.md, gloo/docs/operator_guide/cert-manager.md, gloo/static/css/theme-gloo.css
* left aligned h1 style
* minor content cleanup
=> Enabled all section topics visible

gloo/docs/enterprise/authentication/jwt.md
=> add jwt + rbac guide

squash/docs/debuggers/_index.md, squash/docs/debuggers/gdb.md, squash/docs/debuggers/nodejs.md, squash/docs/debuggers/python_vscode.md, squash/docs/secure_mode/admin.md, squash/docs/secure_mode/user.md
- notes on registering crds
- debugger notes
=> Squash secure mode docs

gloo/docs/installation/_index.md, gloo/docs/installation/gateway/_index.md, gloo/docs/installation/gateway/kubernetes/_index.md, gloo/docs/installation/ingress/_index.md, gloo/docs/installation/knative/_index.md, glooshot/docs/installation/_index.md, sqoop/docs/installation/_index.md, squash/docs/cli/squashctl_completion.md, squash/docs/overview/_index.md, supergloo/docs/installation/_index.md
=> fixed homebrew installation instructions

gloo/docs/user_guides/gateway/tcp_proxy/_index.md
some reason the block
` ``yaml
{{< highlight yaml "hl_lines=23-27" >}} 
wasn't rendered
=> minor tcp fixes

gloo/docs/user_guides/gateway/function_routing/aws_upstream.md
add the `-n gloo-system` and change the dest-name values.
=> fixed some bug 

gloo/docs/gloo_integrations/ingress/_index.md, gloo/docs/installation/ingress/_index.md
includes some simplifications & drop the requirement for ingress class annotation
=> Update ingress docs

gloo/docs/gloo_routing/virtual_services/authentication/external_auth/_index.md, gloo/docs/installation/enterprise/_index.md
quick docs PR to show users new config for extauth over UDS instead of TCP. much less latency!
=> Add docs for extauth sidecar

gloo/docs/gloo_routing/virtual_services/authentication/_index.md
this was in the previous version of docs and bringing it back to the new organized docs
=> add context to Auth main page

gloo/docs/installation/gateway/docker-compose-file/_index.md
Installation directory is `/installation/gateway/docker-compose-file` and not `/installation/gateway/docker-compose`
Signed-off-by: Vinay Bhalerao vinaybhalerao.20@gmail.com
=> Fix directory name

gloo/docs/gloo_integrations/service_mesh/gloo_app_mesh.md
I updated the documentation based on the latest example from AWS official documentation.
=> New version of the Integration app mesh documentation

gloo/docs/dev/writing_auth_plugins/_index.md, gloo/docs/gloo_routing/virtual_services/authentication/plugin_auth/_index.md
Update user and dev guides to reflect recent changes in API, plus some fixes/improvements.
=> Update auth plugin docs

gloo/docs/gloo_routing/virtual_services/rate_limiting/_index.md
Do not merge until we release v0.18.29+ of Gloo Enterprise
=> Add docs for dynamodb-backed rate limiting

gloo/docs/gloo_routing/virtual_services/rate_limiting/envoy/_index.md
=> Fix typo in rate limit docs

gloo/docs.toml, gloo/docs/gloo_routing/virtual_services/rate_limiting/envoy/_index.md, gloo/docs/gloo_routing/virtual_services/security/custom_auth/_index.md, gloo/docs/gloo_routing/virtual_services/security/jwt/access_control.md, gloo/docs/gloo_routing/virtual_services/security/oauth/dex/_index.md, gloo/docs/gloo_routing/virtual_services/security/opa/_index.md, gloo/docs/installation/enterprise/_index.md, gloo/docs/installation/gateway/kubernetes/_index.md, gloo/docs/installation/ingress/_index.md, gloo/docs/installation/knative/_index.md
cc @EItanya @rickducott 
just looking for a quick update
=> Unified cli

gloo/docs/gloo_routing/virtual_services/routes/routing_features/append_remove_headers/_index.md, gloo/docs/gloo_routing/virtual_services/routes/routing_features/prefix_rewrite/_index.md
resolves: https://github.com/solo-io/gloo/issues/1257
also fixes broken link to envoy docs
cc @mitchdraft
=> Improve rewrite docs

gloo/docs/gloo_routing/gateway_configuration/waf/_index.md
=> Fix broken waf doc step

gloo/docs/gloo_routing/virtual_services/security/_index.md, gloo/docs/gloo_routing/virtual_services/security/configuration_format_history/_index.md, gloo/docs/static/content/extauth_version_info_note
First part of the extauth doc update.
=> Improve extauth config format history

gloo/docs/gloo_routing/virtual_services/security/ldap/_index.md, gloo/docs/gloo_routing/virtual_services/security/ldap/vs-auth-ldap.sh, gloo/docs/gloo_routing/virtual_services/security/ldap/vs-auth-ldap.yaml, gloo/docs/gloo_routing/virtual_services/security/ldap/vs-echo-no-auth.sh, gloo/docs/gloo_routing/virtual_services/security/ldap/vs-echo-no-auth.yaml, gloo/docs/static/content/extauth_version_info_note
Updated the LDAP extauth docs to use the latest configuration format.
=> Update LDAP auth docs

gloo/Makefile, gloo/docs/gloo_routing/validation/_index.md
repro docs push failure:
- revert this commit
- run the following:
```
cd gloo
rm -rf themes/hugo-theme-soloio/
make site -B
```
=> update theme checkout logic now that hash is not at master

glooshot/Makefile, sqoop/Makefile, squash/Makefile, supergloo/Makefile, testrepo/Makefile
until we move all the docs to their repos, we need this theme pull fix
=> fix import sequence

gloo/docs/introduction/faq.md
Removed this bullet as it seemed incomplete
* [Web console to manage the control plane]TODO - enterprise feature
=> Remove a "TODO" item from Diff btn Gloo and Envoy

gloo/data/Solo.yaml, glooshot/data/Solo.yaml, sqoop/data/Solo.yaml, squash/data/Solo.yaml, supergloo/data/Solo.yaml, testrepo/data/Solo.yaml
this fixes the search by populating the theme's new shortcodes correctly
=> populate templates

gloo/docs/gloo_routing/virtual_services/rate_limiting/_index.md, gloo/docs/gloo_routing/virtual_services/rate_limiting/enterprise/_index.md, gloo/docs/gloo_routing/virtual_services/rate_limiting/envoy/_index.md, gloo/docs/gloo_routing/virtual_services/rate_limiting/simple/_index.md
docs for custom rate-limit service in open-source gloo
=> Custom rate limit OSS docs

gloo/docs/dev/CONTRIBUTING.md
cc @mitchdraft 
slack context: https://solo-io.slack.com/archives/CEA6QSYV6/p1571722904007800?thread_ts=1571612424.007400&cid=CEA6QSYV6
=> Add docs for changelog to dev guide
